Alignment of footer adderess
IMGIITRoorkee/Easysell-website pull request #33
Opened 2024-12-17 15:23 UTC by anshkarwasra

**Related Issue**

**Closes #27** 
**Type of Change**

- [ ] New Feature

- [X] Bug Fix

- [ ] Code Refactor

  

- [ ] Documentation Update

**Description of Change**
 re-aligned the footer's contact section

**Implementation Details**
instead of grid made .row1 container a flex and set `flex-direction: column` and inserted logo and corresponding text in pair-wise 3 divs of classname .footerTxtWrapper and made them inline-flex element and used  `align-items:center` property on them

2024-12-18 13:12 UTC, sasmitaditya13 commented
Attach a screenshot/working video of your change.

2024-12-18 15:30 UTC, anshkarwasra commented
![Uploading Screenshot 2024-12-18 205958.png…]()

2024-12-18 15:58 UTC, sasmitaditya13 commented
Unable to view the screenshot

2024-12-18 22:19 UTC, nitininhouse commented
@anshkarwasra check size of the icon from the figma file

2024-12-20 11:48 UTC, Yash-g2310 reviewed
@anshkarwasra you have included the changes of your previous 2 pr's in this pr as well
please remove it 
and also as visible from your screen shot that the logos don't match the figma please correct that as well
for any problem fell free to ask at [discord](https://discord.gg/aKaEbaVYKf)

2024-12-21 03:01 UTC, anshkarwasra commented
fixed

2024-12-26 08:22 UTC, Yash-g2310 requested changes
@anshkarwasra these are the changes required,
and here is the [figma link](https://www.figma.com/design/Tnep6rHkErd8BrVc5Rk4R6/HTML-CSS-Design?node-id=1-2109&t=Eb5D9HJQ5vah5Ynh-0)

2024-12-26 08:22 UTC, Yash-g2310 commented on resources/css/landingpage.css
> +    gap: 10px;
you have to maintain overall gap of 36 b/w icons, since you have used 16 as margin, adjust it accordingly?

2024-12-26 08:22 UTC, Yash-g2310 commented on resources/css/landingpage.css
> +    font-size: 12px;
why? 12 px? see the figma file, size is something else

2024-12-26 08:22 UTC, Yash-g2310 commented on resources/css/landingpage.css
> +    height: 50px;
both height and width are 48px, see figma

2024-12-26 08:32 UTC, anshkarwasra commented
Okay and  sorry I didn't know how to access figma styles i tried to make by only looking at its design

2025-01-05 14:05 UTC, Yash-g2310 commented
@anshkarwasra no problem if you didn't had the figma link, it's available in the readme.md in the main directory 
also have you done the changes that I mentioned, please do that so i can merge the code then

2025-01-07 07:12 UTC, closed without merging