Removed inline style in HTML and added it to CSS #23
IMGIITRoorkee/Easysell-website pull request #49
Opened 2024-12-17 22:38 UTC by Akshat1276

### Related Issue  
Closes #23 

### Type of Change
- [ ] New Feature  
- [ ] Bug Fix  
- [X] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
Removed inline style in HTML found in `<div class="abc">` and `<div class="ijk">` and added it to CSS

2024-12-19 19:44 UTC, Hardik-2311 commented
@Akshat1276 Could you please share a screenshot of your screen after making the changes, demonstrating the desired behavior?

2024-12-20 03:50 UTC, Akshat1276 commented
Shared the screenshots sir.

2024-12-20 17:44 UTC, Yash-g2310 requested changes
@Akshat1276  i have mentioned the change required 
![image](https://github.com/user-attachments/assets/56a979e3-6bbb-4c7a-b387-0983be121dcf)
as you can see without it it is creating a bit of a mess
please change this asap
if any doubt head to [easysell discord](https://discord.gg/aKaEbaVYKf)

2024-12-20 17:44 UTC, Yash-g2310 commented on index.html
> +                <div class="abc"><a href="#"><i class="fa fa-2x fa-en></i></a></div>
hey @Akshat1276  there are few issues with your commits
firstly there is a missing ' " ' here and the class name is also not set properly (match with the actual code)

2024-12-20 18:41 UTC, Yash-g2310 commented
solved by someone else, thanks for contributing !

2024-12-20 18:41 UTC, Yash-g2310 commented
solved by someone else, thanks for contributing !

2024-12-20 18:41 UTC, closed without merging