Added about us and our ethos text
IMGIITRoorkee/Easysell-website pull request #72
Opened 2024-12-23 19:15 UTC by Moon-deity

### Related Issue  
Closes #26 number  

### Type of Change
Put `x` inside the square bracket to specify what type of change your PR is:  
- [x] New Feature  
- [ ] Bug Fix  
- [ ] Code Refactor  
- [ ] Documentation Update  
- [ ] Other (please specify): 

### Description of Change  
added about us and our ethos text

### Implementation Details  
changed aboutus.html and aboutus.css and created changeaboutcontent.js

### Demo  
![Screenshot 2024-12-24 004305](https://github.com/user-attachments/assets/b88e3c8a-1ddf-4266-8bcf-bf9bd240cad7)
![Screenshot 2024-12-24 004443](https://github.com/user-attachments/assets/816cac1c-e7d0-4572-adfe-f9916e8a0f5f)

2025-01-07 07:33 UTC, sasmitaditya13 commented
@Yash-g2310 please check the responsiveness of the changes made.

2025-01-12 17:15 UTC, Yash-g2310 requested changes
@Moon-deity  
the changes are good,  just a couple of things,
1. see the correct font weight of the headings from figma
2. in mobile view the alignment of the description is center not left
![image](https://github.com/user-attachments/assets/4d34021e-6938-4f41-8b78-80a11dc5df0b)
please make these 2 changes here is the [figma link](https://www.figma.com/design/Tnep6rHkErd8BrVc5Rk4R6/HTML-CSS-Design?node-id=1-2235&t=Z8P1lbZcP9BIjt5l-0)

2025-01-12 17:30 UTC, Moon-deity commented
@Yash-g2310 
In mobie view alignment of text is center but it seems on the left because larger words are not fitting properly (you can see the screenshot I added above, it's of the same page in mobile view)

2025-01-12 17:36 UTC, Yash-g2310 commented
@Moon-deity 
![image](https://github.com/user-attachments/assets/71065e74-dab3-4ed4-ab2e-296d6c738245)
when the text would be centered it would look something like this
![image](https://github.com/user-attachments/assets/f12f07b3-1599-4dab-8f2b-466712fef1f5)
but there is not text align property currently please check!!

2025-01-12 18:19 UTC, Moon-deity commented
@Yash-g2310 
Please check it now

2025-01-12 18:48 UTC, Yash-g2310 commented
Changes are nice we would be merging it soon

2025-01-14 11:20 UTC, merged